---
title: "Energy Distance Clustering of GDP Data"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We demonstrate the clustering method for the `gdp` dataset provided with this package, sourced from [https://www.conference-board.org/us/](https://www.conference-board.org/us/).

```{r setup}
library(eclust)
gdp
```

We preprocess the data to obtain the log returns of the gdp.

```{r}
gdp_log_return <-
  gdp |>
  dplyr::group_by(country) |>
  dplyr::mutate(gdp = log(gdp) - dplyr::lag(log(gdp))) |>
  tidyr::drop_na() |>
  dplyr::mutate(gdp = as.numeric(scale(gdp))) |>
  dplyr::rename(gdp_logreturn = gdp) |>
  dplyr::ungroup() |>
  tsibble::tsibble(key = country, index = year)
```

Calculate the energy distance based dissimilarity matrix.

```{r}
dist_mat <- edist(gdp_log_return, lag = 1)
```

Perform hierarchical clustering and display the obtained dendrogram.

```{r}
library(ggplot2)
hc <- stats::hclust(dist_mat, method = "ward.D2")
plot(hc)
```