// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// energy_distance_xy
double energy_distance_xy(NumericMatrix x, NumericMatrix y, int h, double a);
RcppExport SEXP _eclust_energy_distance_xy(SEXP xSEXP, SEXP ySEXP, SEXP hSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(energy_distance_xy(x, y, h, a));
    return rcpp_result_gen;
END_RCPP
}
// energy_distance_mat
NumericMatrix energy_distance_mat(NumericMatrix mat, NumericVector sizes, NumericVector h, double a);
RcppExport SEXP _eclust_energy_distance_mat(SEXP matSEXP, SEXP sizesSEXP, SEXP hSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sizes(sizesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(energy_distance_mat(mat, sizes, h, a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eclust_energy_distance_xy", (DL_FUNC) &_eclust_energy_distance_xy, 4},
    {"_eclust_energy_distance_mat", (DL_FUNC) &_eclust_energy_distance_mat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_eclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
